golang-fips/openssl

go.mod, openssl/aes.go, openssl/aes_test.go, openssl/doc.go, openssl/ecdsa.go, openssl/goopenssl.h, openssl/hmac.go, openssl/hmac_test.go, openssl/notboring.go, openssl/openssl.go, openssl/openssl_ecdsa_signature.c, openssl/openssl_evp.c, openssl/openssl_lock_setup.c, openssl/openssl_port_aead_gcm.c, openssl/openssl_port_ctr128.c, openssl/openssl_port_evp_md5_sha1.c, openssl/openssl_port_hmac.c, openssl/openssl_port_rsa.c, openssl/openssl_stub_rand.c, openssl/rand.go, openssl/rsa.go, openssl/sha.go
This PR adds initial code from the golang-fips/go repo. It takes the latest iteration of our changes and puts them in their own package, `openssl`, which we will later import into the main Go crypto packages via a patch to be carried.
=> Add initial code from golang-fips/go

openssl/goopenssl.h, openssl/openssl.go
This transplants https://github.com/golang-fips/go/pull/10 except the last commit fixing `size_t` confusion for review easiness.
=> goopenssl.h: fix wrapper definitions to be compatible with OpenSSL headers

openssl/openssl.go, openssl/sha.go
When boring was merged into the main branch for go1.19
a few new symbols were added. Adding them into this
repo in order to create our Go 1.19 branch.
=> Add new symbols for go1.19 compat

openssl/aes.go, openssl/bbig/big.go, openssl/doc.go, openssl/ecdh_test.go, openssl/ecdsa.go, openssl/goopenssl.h, openssl/notboring.go, openssl/openssl.go, openssl/rsa.go
There are more changes necessary to support Go 1.19 and many of them are backwards incompatible as there are function signature changes. This patch introduces a series of changes to support Go 1.19 but will not be backwards compatible with older versions.
This is acceptable because we only intend to support Go 1.19+ using this particular architecture.
=> Add Go 1.19 support

openssl/goopenssl.c, openssl/goopenssl.h, openssl/openssl.go, openssl/openssl_test.go, openssl/shims.h
This PR adds two new exported functions, `FIPS() bool` and `SetFIPS(enabled bool) error`, both ported from `microsoft/go-crypto-openssl`.
`golang-fips/openssl-fips` also implements `FIPS()` in the unexported [fipsModeEnabled](https://github.com/golang-fips/openssl-fips/blob/60f04d7f65e2dacaaed870f38db900807caf37f0/openssl/openssl.go#L82). The problem is that ir relies on `FIPS_mode()`, which works on OpenSSL 1.x,  but has been removed from OpenSSL 3. RedHat could probably use it because their OpenSSL 3 binaries are patched to support this function, but we can't generally assume it will be there.
I've used instead a combination of tips explained in https://wiki.openssl.org/index.php/OpenSSL_3.0#Using_the_FIPS_Module_in_applications:
- First check …
=> Implement FIPS() and SetFIPS()

openssl/evp.go, openssl/goopenssl.h, openssl/openssl.go, openssl/sha.go, openssl/sha_test.go, openssl/shims.h
This PR implements `NewSHA1`, `NewSHA224`, `NewSHA256`, `NewSHA384`, `NewSHA512`, and their corresponding one-shot versions.
It is a clean port from Microsoft repo, which is built on top of RedHat implementation, with the following changes:
- Remove all legacy SHA OpenSSL functions and objects (`SHA512_CTX`, `SHA384_Init()`, `SHA512_Update()`, etc.) and use only the EVP interface (`EVP_MD_PTR`, `EVP_DigestInit`, `EVP_DigestUpdate`, etc.).
- Support `UnmarshalBinary` and `MarshalBinary` for OpenSSL 3, which stores the sha state in a different place than OpenSSL 1.x.
This time I'll wait for a +1 from @ueno 😄
=> Implement NewSHAX and one-shot SHAX

openssl/openssl.go, openssl/rand.go, openssl/sha.go, openssl/shims.h
This PR implements `newOpenSSLError` using RedHat code with the following modifications:
- Do not export the function, there is no need to call it from outside.
- Use plain string concatenation and `strconv` instead of `fmt` to construct the error message. Upstream try to avoid importing `fmt` in low level crypto packages, so do we.
-  RedHat code appends the error flags to the error string. These flags don't give information about the error, but about the error data, which we don't use. Therefore, we can use `ERR_get_error_line` instead of `ERR_get_error_line_data` and skip also the flags.
-  The formatted error string has been modified to be more *idiomatic*. Example:
```
panic: FIPS_mode_set
openssl error(s):
error:0F06D065:common libcrypto routines:FIPS_mode_set:fips mode not …
```
=> Implement newOpenSSLError

openssl/goopenssl.h
This fixes confusions in using DEFINEFUNC and DEFINEFUNCINTERNAL to define fallback functions for OpenSSL 1.0.2.
Fixes: #33 
Signed-off-by: Daiki Ueno <dueno@redhat.com>
=> Fix compilation error due to missing symbols in OpenSSL 1.0.2

openssl/ecdsa.go, openssl/goopenssl.h, openssl/openssl_ecdsa_signature.c, openssl/openssl_evp.c, openssl/openssl_port_rsa.c, openssl/rsa.go
This makes the internal wrapper functions around OpenSSL functions consistently use `size_t` (or `size_t *`) where appropriate, instead of `unsigned int` (or `unsigned int *`).
The previous code had an issue on 64-bit big-endian systems where `sizeof(size_t)` is longer than `sizeof(unsigned int)` is 32, as the value returned through `unsigned int *` were truncated.
=> Fix integer size confusion

openssl/openssl.go
The conversion code between `BigInt` (= `[]uint`) and OpenSSL
`BIGNUM *` currently assumes that the uint array can be safely
accessed as `[]byte`.  While this is the case on little-endian
platforms, it requires reversal of each limb on big-endian
platforms (note that the ordering of limbs is always LSB first).
Signed-off-by: Daiki Ueno <dueno@redhat.com>
=> bbig: Reverse limbs depending on host endianness

openssl/bbig/big.go, openssl/big.go, openssl/evp.go, openssl/openssl.go, openssl/rsa.go, openssl/rsa_test.go, openssl/shims.h
This PR implements the RSA API. The implementation is taken from the MSFT repo, which was heavily based on RedHat version.
Some comments for the reviewers:
- `SignRSAPKCS1v15` and `VerifyRSAPKCS1v15` function signatures are the ones defined by Boring, so they expect the message to be hashed and don't define the `msgIsHashed` parameter.
- I've added the functions `HashSignRSAPKCS1v15` and `HashVerifyRSAPKCS1v15` to cover the on-shot hash+sign use-case. Deciding which function to use is left to the backend layer.
- The `RSA_set0_factors`, `RSA_set0_crt_params`, and friends' fallbacks for OpenSSL 1.0.2 are implemented on the Go side instead of on the C side, following the logic that Go is safer and easier to maintain than C.
- I'm aware that #42 also affects the logic in this PR. I'll cherry …
=> Implement RSA

openssl/ecdsa.go, openssl/ecdsa_test.go, openssl/evp.go, openssl/openssl.go, openssl/openssl_test.go, openssl/rsa.go, openssl/shims.h
⚠️ This PR will be rebased once #43 is merged. Please review #43 first.
This PR implements the ECDSA API. The implementation is taken from the MSFT repo, which was heavily based on RedHat version.
Some comments for the reviewers:
- I've added the functions `HashSignRSAPKCS1v15` and `HashVerifyRSAPKCS1v15` to cover the on-shot hash+sign use-case. Deciding which function to use is left to the backend layer.
=> Implement ECDSA

openssl/hkdf.go
This commit introduces a function that returns true or false depending on whether the OpenSSL version is expected to support HKDF. It is expected to be used by the crypto/tls library to help determine whether TLS version 1.3 can be used in FIPS mode.
=> Add SupportsHKDF()

openssl/rsa.go
`GenerateKeyRSA` calls `EVP_PKEY_get1_RSA` without freeing the returned pointer, causing a leak.
=> Fix memory leak in GenerateKeyRSA

.github/workflows/test.yml, cmd/checkheader/main.go, openssl/ecdh.go, openssl/ecdh_test.go, openssl/ecdsa.go, openssl/evp.go, openssl/goopenssl.h, openssl/openssl.go, openssl/params.go, openssl/shims.h
This PR implements the ECDH functions.
@derekparker @ueno I haven't ported `SharedKeyECDH` function. For what I can see, it was only used to support OpenSSL ECDH on `crypto/tls`. Go1.20 implements ECDH using the new `crypto/ecdh` package, so it would be easier for you to just use the ECDH functions from this PR than trying to retrofit `SharedKeyECDH`. Please correct me if I'm wrong, in which case I'll try to port it.
=> Implement ECDH

.gitleaks.toml
This adds a configuration file for GitLeaks secret scanning to ignore false-positives:
```console
$ ./gitleaks detect -v -s ../openssl-fips
...
{
"Description": "Generic API Key",
"StartLine": 87,
"EndLine": 87,
"StartColumn": 11,
"EndColumn": 81,
"Match": "Key: ...",
"Secret": "...",
"File": "openssl/ecdh_test.go",
```
=> Add GitLeaks configuration

.gitleaks.toml, openssl/ecdh.go, openssl/ecdh_test.go, openssl/evp.go, openssl/goopenssl.h, openssl/notboring.go, openssl/params.go
This backports the ECDH implementation from
wip/combined-codebase-staging, as it better suits Go 1.20 crypto/ecdh
interface.
=> Backport ECDH implementation from wip/combined-codebase-staging

openssl/ecdh.go, openssl/hmac.go, openssl/params.go, openssl/rsa_test.go, openssl/shims.h
This PR updates the HMAC implementation to use `EVP_MAC_CTX` on OpenSSL 3 instead of the deprecated `HMAC_CTX`.
While here, I've changed how OpenSSL 1 resets the context to avoid having to keep the key around. [HMAC_Init_ex](https://www.openssl.org/docs/man1.0.2/man3/HMAC_Init_ex.html) reuses the same key and hash function if they are not passed, as `Reset()` is not changing those parameters, there is no need to pass them.
> HMAC_Init_ex() initializes or reuses a HMAC_CTX structure to use the hash function evp_md and key key. If both are NULL (or evp_md is the same as the previous digest used by ctx and key is NULL) the existing key is reused. ctx must have been created with HMAC_CTX_new() before the first use of an HMAC_CTX in this function. N.B. HMAC_Init() had this undocumented …
=> Implement HMAC using EVP_MAC_CTX on OpenSSL 3

openssl/ecdh.go, openssl/ecdsa.go, openssl/openssl.go, openssl/params.go
The wrapper `bnFree` was there only to guard `BN_free` from a potentially
NULL argument, while `BN_free` actually takes care of it as it follows
the same semantics of free.
=> Remove wrapper around BN_free

openssl/ecdh.go, openssl/ecdsa.go
This adds zeroization of critical security parameters in ECDH and ECDSA operations, to comply with the FIPS 140-3 requirements.
=> ecdh, ecdsa: Make sure to clear private BIGNUM values

openssl/goopenssl.h, openssl/notboring.go, openssl/openssl_evp.c, openssl/openssl_port_rsa.c, openssl/rsa.go, openssl/rsa_test.go
For creating and verifying PKCS#1 v1.5 signatures in a pre-hashed manner, we used the legacy `RSA_sign` and `RSA_verify` functions, which bypass the system-wide disablement of SHA-1 and shorter RSA key length usage inconsistently with the OpenSSL 3.0 default on RHEL.
This switches to using our `_goboringcrypto_EVP_{sign,verify}_raw`, which internally use `EVP_PKEY_` functions.
=> Stop using RSA_* functions for signatures

openssl/sha.go, openssl/sha_test.go
This PR implements WriteString and WriteByte for all supported hashers. These methods will be required by the boring API in go1.21.
See [CL 483816](https://go-review.googlesource.com/c/go/+/483816), [483815](https://go-review.googlesource.com/c/go/+/483815), and [CL 481478](https://go-review.googlesource.com/c/go/+/481478).
=> sha: add WriteString and WriteByte method

openssl/ecdsa.go, openssl/ecdsa_test.go, openssl/goopenssl.h, openssl/notboring.go, openssl/openssl_ecdsa_signature.c
This removes the usage of EC_KEY_* functions for cryptographic operations mainly to enforce FIPS restrictions; for accessors, some of them are still used. The first two commits are from #57.
=> Stop using deprecated EC functions for ECDSA

.github/workflows/test.yml, openssl/goopenssl.c, openssl/goopenssl.h, openssl/init.go, openssl/openssl.go, openssl/openssl_test.go, openssl/shims.h
This PR removes the fallback logic of `openssl.Init("")`, which would try to load OpenSSL versions from a list of well-known shared library sufixes. The reasoning to do so is that the fallback process assumes all Go forks using `openssl-fips` have the same OpenSSL requirements and priorities, and that the list is static and hardly changes. For example, the MSFT Go fork wants to prioritize FIPS-enabled OpenSSL versions, even if it's not the highest available version.
A better approach, implemented also in this PR, is to expose the necessary functions so the caller always calls `openssl.Init` with the right version. To do so, I've implemented `openssl.CheckVersion`, which checks if a given version exists and is FIPS capable.
Downstream users could implement the initialization process as …
=> Remove Init fallback logic and provide CheckVersion instead

port_evp_md5_sha1.c
The Microsoft fork fails to bootstrap on Windows if `port_evp_md5_sha1.c` is not excluded from the build.
=> Exclude port_evp_md5_sha1.c from non-linux OSes

hmac_test.go, rsa_test.go, sha_test.go
Some tests using `t.Parallel` are not behaving as expected due to a loop variable being captured by a function closure.
=> Fix loopclosure vet check

evp.go
This PR implements the following OpenSSL performance guidelines:
- EVP_MD objects should be fetched just once and used for multiple calls to other operations such as EVP_DigestInit_ex().
- (For OpenSSL 3) If you perform the same operation many times then it is recommended to use ["Explicit fetching"](https://www.openssl.org/docs/man3.0/man7/crypto.html#Explicit-fetching) to prefetch an algorithm once initially, and then pass this created object to any operations that are currently using ["Implicit fetching"](https://www.openssl.org/docs/man3.0/man7/crypto.html#Implicit-fetching).
See ["Performance" in crypto(7)](https://www.openssl.org/docs/man3.0/man7/crypto.html) for further information.
=> Cache and pre-fetch EVP_MD objects

aes.go, evp.go, shims.h
Same as #75 but for `EVP_CIPHER` objects,
=> Cache and pre-fetch EVP_CIPHER objects

hmac.go
This PR improves `NewHMAC` so it reuses the same `EVP_MAC` object instead of fetching it every time.
Doing so also fixed a memory leak: the object returned by `EVP_MAC_fetch` should have been freed using `EVP_MAC_free`. The new approach doesn't require freeing that object, as it is kept as a global variable to be reused later on.
Thanks to caching, `NewHMAC` is now ~9% faster:
```go
goos: linux
goarch: amd64
pkg: github.com/golang-fips/openssl
cpu: AMD EPYC 7763 64-Core Processor                
│   old.txt   │              new.txt               │
│   sec/op    │   sec/op     vs base               │
NewHMAC-16   4.616µ ± 1%   4.199µ ± 1%  -9.04% (p=0.000 n=20)
```
=> Cache HMAC object and fix memory leak

.github/workflows/test.yml, hmac.go, scripts/openssl.sh
This PR optimizes `opensslHMAC.Reset` for OpenSSL 3.0.3 and higher versions, in which we don't have to pass the key thanks to https://github.com/openssl/openssl/issues/17811 being fixed.
The perf wins are remarkable:
```cmd
goos: linux
goarch: amd64
pkg: github.com/golang-fips/openssl
cpu: AMD EPYC 7763 64-Core Processor                
│   old.txt   │               new.txt               │
│   sec/op    │   sec/op     vs base                │
HMACSHA256_32-16     1.338µ ± 0%   1.093µ ± 2%  -18.32% (p=0.000 n=10)
HMACNewWriteSum-16   5.296µ ± 3%   5.374µ ± 4%        ~ (p=0.529 n=10)
geomean              2.661µ        2.423µ        -8.95%
│   old.txt    │               new.txt                │
│     B/s      │     B/s       vs base                │
HMACSHA256_32-16     22.82Mi ± 0% …
```
=> hmac: avoid passing the key when calling Reset() on OpenSSL 3.0.3+

sha.go
This is a continuation PR of #75, in which I missed to reuse the `EVP-MD` objects on one-shot functions.
The perf improvement is noticeable:
```cmd
goos: linux
goarch: amd64
pkg: github.com/golang-fips/openssl
cpu: AMD EPYC 7763 64-Core Processor                
│   old.txt   │               new.txt               │
│   sec/op    │   sec/op     vs base                │
SHA256-16   549.4n ± 1%   287.9n ± 1%  -47.59% (p=0.000 n=10)
│   old.txt    │               new.txt                │
│     B/s      │     B/s       vs base                │
SHA256-16   13.89Mi ± 1%   26.49Mi ± 1%  +90.80% (p=0.000 n=10)
│  old.txt   │            new.txt             │
│    B/op    │    B/op     vs base            │
SHA256-16   0.000 ± 0%   0.000 ± 0%  ~ (p=1.000 n=10) ¹
¹ all samples are equal
│  old.txt   │ …
```
=> sha: reuse cached EVP_MD on one-shot functions

goopenssl.h, sha.go, shims.h
This PR is a clean-up opportunity I saw recently. We don't need to implement a one-shot digest function ourselves, all supported OpenSSL versions already provide [EVP_Digest](https://www.openssl.org/docs/man3.0/man3/EVP_Digest.html). This function has the nice benefit of being a little bit faster on OpenSSL 3, thanks to setting the `EVP_MD_CTX_FLAG_ONESHOT` flag.
```cmd
goos: linux
goarch: amd64
pkg: github.com/golang-fips/openssl
cpu: AMD EPYC 7763 64-Core Processor                
│   new.txt   │              new2.txt              │
│   sec/op    │   sec/op     vs base               │
SHA256-16   287.9n ± 1%   283.8n ± 1%  -1.46% (p=0.003 n=10)
│   new.txt    │              new2.txt               │
│     B/s      │     B/s       vs base               │
SHA256-16   26.49Mi ± 1%   26.89Mi …
```
=> sha: use EVP_DIGEST instead of go_shaX

sha.go
There is a possible use-after-free issue in `evpHash.WriteString` and in `evpHash.WriteByte`. They both pass `h.ctx` to `EVP_DigestUpdate` without making sure `h` is still alive until the cgo call ends, i.e. using `runtime.KeepAlive(h)`.
If the garbage collector chimes in at the right time, it will collect `h`, calling it's finalizer, that free's `h.ctx`, likely producing an invalid access exception.
Ported from https://github.com/microsoft/go-crypto-openssl/pull/55.
=> sha: fix use-after-free issue

rsa.go, shims.h
This PR updates `GenerateKeyRSA`, `NewPublicKeyRSA`, and `NewPrivateKeyRSA` so they don't use deprecated OpenSSL 3 APIs when constructing a RSA key.
=> rsa: don't use deprecated OpenSSL APIs to contruct keys

cmd/checkheader/main.go, goopenssl.c, goopenssl.h, shims.h, thread_setup.c
This PR doesn't change functionality, but makes sure that all functions I've identified as deprecated in OpenSSL 3 are defined using the `DEFINEFUNC_LEGACY_1` macro, which will ensure we only use it in OpenSSL 1 code paths.
While here, I've removed a couple of unused functions.
Update: I've added the macro `DEFINEFUNC_LEGACY_1_1`, which can be used to define functions only available (and not deprecated) in OpenSSL 1.1.x. Thanks to that, we can now say that we don't use any deprecated function for any given OpenSSL version. Additionally, I've updated `checkheader` to validate that this remains true forever by using the `-DOPENSSL_NO_DEPRECATED` flag.
Update 2: Thanks top the previous check, I've found that `CRYPTO_set_id_callback` is deprecated in OpenSSL 1.0.2 We should be using …
=> Enforce using only non-deprecated functions

cmd/checkheader/main.go, evp.go, goopenssl.c, goopenssl.h, init.go, sha.go, sha_test.go, shims.h, xcrypto/sha3/sha3.go
This adds OpenSSL SHA-3 family of hashes in the openssl package.
Separately sha3 package is added as a drop-in replacement for golang.org/x/crypto/sha3 package.
Together with FIPS-compliant Go toolchain one can thus attempt building FIPS-compliant applications that use "crypto" package and also need FIPS-compliant SHA-3.
Ideally, a patched golang toolchain will use openssl/xcrypto/sha3 in place of any imports of golang.org/x/crypto/sha3, this is a future improvement to ensure golang-fips toolchain provides FIPS SHA3 without source changes.
Fixes: https://github.com/golang-fips/openssl/issues/87
=> sha: Add SHA3 implementation

README.md, aes.go, aes_test.go, ec.go, ecdh.go, ecdh_test.go, ecdsa.go, ecdsa_test.go, evp.go, goopenssl.c, hkdf.go, hkdf_test.go, hmac.go, hmac_test.go, init.go, openssl.go, openssl_test.go, port_evp_md5_sha1.c, rand.go, rand_test.go, rsa.go, rsa_test.go, sha.go, sha_test.go, thread_setup.c
The `!android` build tag was inherited from the `boring` package, which doesn't support Android. OpenSSL does support building on Android, see [docs](https://github.com/openssl/openssl/blob/master/NOTES-ANDROID.md), so we shouldn't be artificially limiting the allowed environments.
This PR is more of a cleanup PR than a feature request, AFAIK no one is using it on Android devices yet.
=> remove !android build tag

.github/workflows/test.yml, aes.go, aes_test.go, ec.go, ecdh.go, ecdh_test.go, ecdsa.go, ecdsa_test.go, evp.go, go.mod, goopenssl.c, hkdf.go, hkdf_test.go, hmac.go, hmac_test.go, init.go, openssl.go, openssl_test.go, port_evp_md5_sha1.c, rand.go, rand_test.go, rsa.go, rsa_test.go, sha.go, sha_test.go, thread_setup.c
This module will be first used in go1.21, so we don't have to keep backwards compatibility with older versions.
Once we start using it, bumping the minimum Go version will be potentially more disruptive, better do it now.
=> Bump minimum Go version to 1.20

bbig/big.go, ecdh_test.go, ecdsa_test.go, go.mod, hkdf_test.go, openssl_test.go, rand_test.go, rsa_test.go, sha_test.go
This PR adds the necessary version suffix to the module name.
Found this issue just after cutting `v2.0.0-rc.1` while integrating it into the Microsoft Go fork.
I'll create a new tag. `v2.0.0-rc.1`, after merging this PR.
=> Add version suffix to the module name

aes.go, ec.go, ecdh.go, ecdsa.go, evp.go, hkdf.go, hmac.go, init.go, openssl.go, rand.go, rsa.go, sha.go
This is necessary for the Red Hat Go fork as our support for building with openssl is opt-out instead of opt-in, meaning it isn't gated behind a build tag. Without this change `./make.bash` will fail.
=> Add !cmd_go_bootstrap tag

evp.go, sha.go, sha_test.go
This PR removes `SupportsSHA3()` and replaces it with `SupportsHash(crypto.Hash)`, which is more future-proof and supports fine-grained hash queries.
=> Generalize checking if a crypto.Hash is supported

tls1prf.go, tls1prf_test.go
`SupportsTLS1PRF` doesn't return true for 1.1.0 nor 1.1.1, and it should.
=> SupportsTLS1PRF should report true for OpenSSL 1.x

cgo_go122.go, ecdh_test.go
`noescape` and `nocallback` are new go1.22 cgo directives that helps the Go compiler take better decisions. See https://github.com/golang/go/issues/56378 for more context.
In this PR I've tagged [EVP_PKEY_derive](https://www.openssl.org/docs/manmaster/man3/EVP_PKEY_derive.html) with both directives, which allows the `keylen` parameter to stay on the stack. `EVP_PKEY_derive` is currently used in ECDH, HKDF and TLS1PRF, so they will all automatically benefit from this optimization.
Benchmark prove for ECDH:
```
goos: windows
goarch: amd64
pkg: github.com/golang-fips/openssl/v2
cpu: Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
│   old.txt    │            new.txt             │
│    sec/op    │    sec/op     vs base          │
ECDH-12   53.01µ ± 12%   53.24µ ± 11%  ~ (p=0.853 n=10)
│  old.txt   │ …
```
=> Add noescape and nocallback directive to EVP_PKEY_derive

tls1prf.go, tls1prf_test.go
This PR updates `TLS1PRF` to accept a byte slice parameter where to write the output. This avoids allocating a new slice on each function call and integrates better with the standard library, which expects the PRF to update an already existing slice: https://github.com/golang/go/blob/2f0b28da1900909a2c3ddf646bb508fc7effb8f2/src/crypto/tls/prf.go#L68.
To make is clear, the current code would have to be integrated like this:
```go
func prf12(hashFunc func() hash.Hash) func(result, secret, label, seed []byte) error {
return func(result, secret, label, seed []byte) error {
if backend.Enabled && backend.SupportsTLS1PRF() {
out, err := backend.TLS1PRF(secret, label, seed, len(result), hashFunc)
if err != nil {
return fmt.Errorf("crypto/tls: prf12: %v", err)
}
copy(result, out)
return nil
}
... …
```
=> tls1prf: require callers to pass in the result buffer

evp.go, rsa_test.go
Found this while running x/crypto `internal/wycheproof` tests using the OpenSSL backend.
* The bug is already reported to OpenSSL:  
https://github.com/openssl/openssl/issues/21288.
The [doc](https://www.openssl.org/docs/man3.1/man3/EVP_PKEY_CTX_set0_rsa_oaep_label.html) is pretty clear that what we were doing should work:
> EVP_PKEY_CTX_set0_rsa_oaep_label() sets the RSA OAEP label to binary data label and its length in bytes to len. If label is NULL or len is 0, the label is cleared.
Also fixes the error message to match the function name.
=> Fix RSA OAEP failure when given empty label with OpenSSL 3

rc4.go, rc4_test.go
I missed this behavior when implementing RC4. If we don't panic before calling `EVP_EncryptUpdate`, OpenSSL throws and corrupts the destination buffer.
=> Panic if rc4 xor'ed buffer doesn't fit into output buffer

evp.go
The label parameter for RSA OAEP is optional and by default it should be empty.  Given that it is set only once in setupEVP, we can bypass the call to EVP_PKEY_CTX_set0_rsa_oaep_label if the label is empty to spare 1-byte memory allocation and the following CGO call.
=> rsa: skip setting label for RSA OAEP if empty

ed25519.go, ed25519_test.go
While integrating Ed25519 into the standard library I noticed that it is not necessary for `GenerateKeyEd25519` to return the public key, as it can already be derived from the private key.
Doing so can help reduces allocations and cgo calls in [ed25519.GenerateKey](https://pkg.go.dev/crypto/ed25519#GenerateKey), depending on how one decides to implement it.
```cmd
goos: windows
goarch: amd64
pkg: github.com/golang-fips/openssl/v2
cpu: Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
│   old.txt    │               new.txt               │
│    sec/op    │   sec/op     vs base                │
Ed25519GenerateKey-12   47.48µ ± 18%   35.97µ ± 7%  -24.25% (p=0.000 n=10)
│  old.txt   │              new.txt               │
│    B/op    │    B/op     vs base                │
Ed25519GenerateKey-12   56.00 …
```
=> Update GenerateKeyEd25519 to only generate a private key

openssl/goopenssl.h, openssl/hmac.go, openssl/hmac_test.go, openssl/openssl_evp.c, openssl/openssl_port_hmac.c, openssl/openssl_port_rsa.c
This makes the HMAC binding use the EVP_DigestSign interface instead of the deprecated HMAC_CTX functions, so that the implementation go through the FIPS provider when used with OpenSSL 3.
=> v1: Port HMAC to using EVP_DigestSign if available

aes.go, aes_test.go, cipher.go
Implements `NewGCMTLS13` by extending `NewGCMTLS` and incorporating the logic described in the boringssl implementation at https://github.com/google/boringssl/blob/d1831d78c867ba51b3992ccc213fd201d2f4b0f1/crypto/fipsmodule/cipher/e_aes.c#L1397-L1403.
https://github.com/golang/go/commit/4106de901a8efe914cda6f6c4e8d45ff8c115da4 is in `master` and the `go1.22rc1` tag, and it depends on a new `NewGCMTLS13` function in the boring backend. I found out about this when it broke our upstream sync CI. It adds crypto/internal/boring `NewGCMTLS13`, calling `_goboringcrypto_EVP_aead_aes_128_gcm_tls13`. It didn't look all that complicated once I got to the boringssl implementation, so I thought I would try writing this PR.
---
The code comment I added is a little long-winded. It took me a bit to …
=> Add NewGCMTLS13 for Go TLS 1.3 support

aes_test.go, cipher.go
* Fixes https://github.com/golang-fips/openssl/issues/133
=> Fix TLS 1.3 additionalData length check

goopenssl.h, shims.h, thread_setup.go, thread_setup.h, thread_setup_test.go, thread_setup_unix.c, thread_setup_windows.c
OpenSSL 1.0.x automatically allocates a per-thread error queue as needed, but requires that the application call ERR_remove_thread_state() when terminating a thread to prevent the memory from leaking. As the Go runtime may create and terminate threads arbitrarily, the amount of memory leaked has the potential to grow unbounded.
Clean up the OpenSSL error queue for a thread upon thread exit. Use the native threading APIs to arrange a callback on thread exit as the Go runtime does not provide any similar facilities itself.
No explicit thread-exit handling is needed for OpenSSL 1.1.0 and above as it automatically deallocates thread-local resources without application assistance. See the OPENSSL_thread_stop(3) man page for more information.
=> Free thread-local OpenSSL state on thread exit

ecdh.go, ed25519.go, goopenssl.h, hkdf.go, tls1prf.go
* For https://github.com/golang-fips/openssl/issues/128
* Replaces the optimization removed in https://github.com/golang-fips/openssl/pull/129
* I prefer this approach over https://github.com/golang-fips/openssl/pull/130, because this approach more faithfully passes data to/from the OpenSSL API to deal with in Go code.
```
goos: linux
goarch: amd64
pkg: github.com/golang-fips/openssl/v2
cpu: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
│   old.txt   │        new-struct.txt        │
│   sec/op    │   sec/op     vs base         │
ECDH-8   104.1µ ± 3%   103.8µ ± 2%  ~ (p=0.878 n=8)
│  old.txt   │          new-struct.txt           │
│    B/op    │    B/op     vs base               │
ECDH-8   40.00 ± 0%   32.00 ± 0%  -20.00% (p=0.000 n=8)
│  old.txt   │          new-struct.txt           │
│ …
```
=> Wrap multi-return APIs using structs: avoid heap escape

rsa.go, rsa_test.go
OpenSSL 3.0 and 3.1 required precomputed values for CRT (Dp, Dq, and Qinv), when the primes (P and Q) are included in the params array.
Since all of them can be derived from N, E, and D, this patch simply stops passing those values if any of them are missing.
See also: https://github.com/openssl/openssl/pull/22334
=> rsa: Allow omission of precomputed values in NewPrivateKeyRSA

thread_setup.go
This file utilizes CGO which causes the bootstrap phase of the compiler build to fail.
=> Add build tag excluding thread_setup.go during bootstrap

.github/workflows/test.yml, README.md, scripts/openssl.sh
This PR extends the test matrix to latest patch version of OpenSSL v3.0, v3.1 and v.3.2.
=> Test using latest openssl v3 minor versions

openssl/ecdsa.go, openssl/ecdsa_test.go, openssl/goopenssl.h, openssl/notboring.go, openssl/openssl_ecdsa_signature.c
This backports #58 to the `go1.20-support` branch, to address golang-fips/go#177.
=> [go1.20-support] Stop using deprecated EC functions for ECDSA

aes_test.go, cipher.go, export_test.go
Fixes https://github.com/golang-fips/go/issues/187
CBC and CTR are left as-is, as we also cached the context in the v1 version, so technically not a regression.
=> cipher: do not reuse cipher ctx for certain operations

.github/workflows/test.yml, scripts/openssl.sh
Increase coverage for 3.3.0, which a team in Microsoft is trying out, and 3.3.1 because it's the latest 3.3 version.
=> Add OpenSSL test versions 3.3.0, 3.3.1

aes_test.go, cipher.go, export_test.go
Fixes https://github.com/golang-fips/go/issues/187
Co-authored-by: Derek Parker <deparker@redhat.com>
(cherry picked from commit 61a53ab338d5f1657c6fe5d856d24528bfdd731d)
Seems like this fix was not cherry-picked yet into microsoft/go 1.22.x branch. Note there will be 1.22.x release this week, so would be nice to get this in.
cc @dagood @gdams ensuring that 1.22.x branch remain on par with https://github.com/microsoft/go/pull/1252 w.r.t. this bugfix
=> cipher: do not reuse cipher ctx for certain operations (#146)

.github/workflows/test.yml, go.mod
Require at least Go 1.22 to build this module. None of the maintainers is using it in a toolchain older than Go 1.22, and there are some new convenient functions that can simplify the code (e.g. [sync.OnceValue](https://pkg.go.dev/sync#OnceValue)).
=> Bump minimum Go version to 1.22

.github/workflows/test.yml
This PR adds a GitHub Actions job that runs on Azure Linux 3.
Azure Linux 3.0 uses the [SymCrypt-OpenSSL](https://github.com/microsoft/SymCrypt-OpenSSL) provider, which has some limitations in terms of supported algorithms. Given that Azure Linux is a first class target for us (the Microsoft maintainers of this module), it would be helpful to run the CI test suit on that distro.
=> Add Azure Linux 3.0 coverage in GitHub Actions

evp.go, hash.go, hash_test.go, shims.h
We can only marshal/unmarshal the internal state of hashers provided by built-in providers, which are the only ones from which we know the memory layout.
This PR does some struct embedding tricks so the hashers returned by`NewMD5`, `NewSHA1`, `NewSHA224`, `NewSHA256`, `NewSHA384`, and `NewSHA512`, only implement the `encoding.BinaryMarshaler` and `encoding.BinaryUnmarshaler` interface if the hashers are provided by the fips or the default provider.
Fixes #156.
=> Only implement encoding.BinaryMarshaler for hashers provided by built-in providers

thread_setup_unix.c
This PR backports #162 to the Microsoft Go 1.23 support branch.
=> [ms-go1.23-support] Use valid address in pthread_setspecific to silence warnings (#162)

ecdsa_test.go
When using the [SymCrypt-OpenSSL](https://github.com/microsoft/SymCrypt-OpenSSL) provider, `openssl.VerifyECDSA` writes to stderr a log message if the ECDSA signature is not correctly DER encoded. That write is not in our code, but in `SymCrypt-OpenSSL`, so we can't make it disappear.
`TestECDSASignAndVerify` currently modifies the first byte of a valid ECDSA signature to test that `openssl.VerifyECDSA` correctly detect invalid signatures. The first byte is part of the DER encoding, so running that test using `SymCrypt-OpenSSL` is very verbose: 
```cmd
go test -v -run TestECDSASignAndVerify/P256
Using libcrypto.so.3
OpenSSL version: OpenSSL 3.3.0 9 Apr 2024
FIPS enabled: false
=== RUN   TestECDSASignAndVerify
=== RUN   TestECDSASignAndVerify/P256
=== PAUSE TestECDSASignAndVerify/P256
=== …
```
=> Avoid SymCrypt provider logs in TestECDSASignAndVerify

export_test.go, openssl.go, rsa_test.go
The SymCrypt provider does not currently support RSA encryption with a distinct MGF1 hash function nor using RSA PKCS1.5 with unhashed messages.
This PR skips the affected tests when the SymCrypt provider is available, which means that it will probably be used and the tests will fail.
=> Skip tests not supported by SymCrypt

ecdsa.go, hash_test.go, rsa.go
In Go, it is a common convention to use lowercase letters for parameter names to maintain consistency and improve readability. 
Solves #165
=> fix:Decapitalize parameters

aes_test.go, block_test.go, des.go, des_test.go, internal/cryptotest/README.md, internal/cryptotest/block.go, internal/cryptotest/hash.go
We missed to panic when a `desCipherWithoutCBC` encryption or decryption failed, which made our DES implementation not conformant with the [cipher.Block](https://pkg.go.dev/crypto/cipher#Block) interface, specially for overlapping inputs.
The fix is really small, see this commit: 9e68e597b7cac57a72912bfdae0e7ad49cada0b2.
The bulk of the changes in this repo are just adding tests to make sure that we don't regress.
Fixes https://github.com/microsoft/go/issues/1290.
While here, fix the 3DES CBC support detection logic, which was backwards.
This PR will have to be backported into the Microsoft Go 1.23 support branch.
=> Panic if DES encryption or decryption fails

aes_test.go, des.go, des_test.go, internal/cryptotest/README.md, internal/cryptotest/block.go, internal/cryptotest/hash.go
This PR backports https://github.com/golang-fips/openssl/pull/169 to the Microsoft Go 1.22 support branch.
=> [ms-go1.22-support] Panic if DES encryption or decryption fails (#169)

hash_test.go, hkdf_test.go, hmac_test.go, openssl.go, openssl_test.go, rsa_test.go, tls1prf_test.go
This pull request addresses an issue with loop variable capturing that was resolved in Go 1.22. Prior to Go 1.22, closures within loops would capture the loop variable itself, leading to unexpected behavior due to the variable's value changing by the time the closure was executed.
Changes Made:
Updated code to align with the new behavior in Go 1.22, where the loop variable's value is captured at each iteration rather than the variable itself.
=> Fix: Loop Variable Capturing Issue in Go 1.22

rsa.go, rsa_test.go
Since OpenSSL 3.2, RSA primes can coexist with empty precomputed values, see https://github.com/openssl/openssl/pull/22334.
Some providers, such as SymCrypt, compute the RSA private key using the prime numbers `P` and `Q` instead of loading it from the private exponent `D`. So they always need `P` and `Q`, even if the precomputed values are omitted. This means that these providers are not fully compatible with OpenSSL 3.0 and 3.1, but they do work with OpenSSL 3.2 and higher.
This PR relaxes the restriction added in #136 to only take effect with OpenSSL 3.0 and 3.1.
=> Only omit RSA primes if precomputed values are missing in OpenSSL 3.0 and 3.1

.github/workflows/test.yml
All tests are passing when executed on Azure Linux 3: https://github.com/golang-fips/openssl/actions/runs/10793057985 🥳 
We now promote it to first-class target by blocking PRs if the `azurelinux` job fails.
=> Fail CI pipeline if azurelinux job fails

hash.go, hash_test.go
This PR resolves issue #148 by implementing the encoding.BinaryAppender interface for our hash functions. In Go 1.24, all hash algorithms are expected to implement this interface, as outlined in the following changeset: [crypto: implement encoding.BinaryAppender for all crypto hashes](https://go-review.googlesource.com/c/go/+/601776).
By adding this interface implementation to our fork, we ensure compatibility with the upcoming Go 1.24 release and future-proof our codebase against breaking changes related to the handling of binary encoding for hash algorithms.
=> Add implementation of encoding.BinaryAppender for hash algorithms

dsa.go, dsa_test.go
Some provider, such as SymCrypt, doesn't support DSA.
This PR implements the `openssl.SupportsDSA` function so callers can check if it is supported or not. Also, use it in the DSA tests.
=> Implement SupportsDSA

hash_test.go
Simplify tests with removing extra conversions and reducing the variable declarations.
Also removing the "skipped:" prefix, since we already calling t.Skip(), we don't need to implement this.
=> Remove multiple interface conversions in tests

evp.go, hash_test.go, hkdf.go, hkdf_test.go, hmac.go, hmac_test.go, pbkdf2.go, pbkdf2_test.go, tls1prf.go, tls1prf_test.go
While testing different provider configurations I found out that we are still panicking instead of returning an error in several places where the desired hash function is not supported by the OpenSSL provider.
This PR fixes all cases where we are calling a user-provided `func() hash.Hash` function that can panic, e.g. when calling `openssl.NewHMAC(openssl.NewSHA224, nil)` with a provider that doesn't support SHA224 (aka SymCrypt).
Our azurelinux CI job hasn't triggered this situation because it is configured to use SymCrypt by default and fall back to the built-in default provider for algorithms that SymCrypt doesn't support. I triggered the error by making the built-in default provider unavailable. Anyway, I've added some tests so that we cover this situation with any provider …
=> Make algorithms more robust to unsupported hashes

params.go, shims.h, tls1prf.go, tls1prf_test.go
The [EVP_KDF](https://docs.openssl.org/master/man3/EVP_KDF/) API was added in OpenSSL 3 to properly support KDF algorithms, such as TLS1 PRF. It is recommended that KDF operations migrates from the EVP_PKEY API to this new API. The built-in providers still support the EVP_PKEY for back compat, but third party provider might not do it (SymCrypt looking at you).
This PR implements TLS1 PRF using the EVP_KDF API when using OpenSSL 3.
Also, I'm introducing a new helper, `paramBuilder`,  to build parameters in a much cleaner and safer way. I'll submit a follow-up PR using this helper in other algorithms.
For #158.
For #189.
=> Implement TLS1 PRF using the EVP_KDF API in OpenSSL 3

.github/workflows/test.yml
Our clients using Mariner 2 have been experiencing panics. To mitigate these issues, this pull request introduces changes to the GitHub workflow YAML file, enabling automated testing on Mariner 2 as well.
=> Add Mariner 2 to Github Workflow

openssl/goopenssl.h, openssl/hmac.go, openssl/openssl_port_hmac.c
EVP_DigestSignFinal requires the length argument to be initialized if the output is non-NULL. This changes the _goboringcrypto_HMAC_Final to take the output length as an input argument, and pass it along to EVP_DigestSignFinal.
=> v1: Fix EVP_DigestSignFinal call for HMAC
